on:
  schedule:
  - cron: '*/30 * * * *'

name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@stable-win
      env:
        SHOVEL: '1'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
